name: ckbalance
description: A wallet for Nervos

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  fluintl: ^0.1.2
  bip39: ^1.0.3
  flutter_secure_storage: ^3.2.0
  shared_preferences: ^0.5.1+1
  encrypt: ^2.0.0
  bip32: ^1.0.5
  qr_flutter: ^2.0.0+51
  ckb_sdk:
    git:
      url: https://github.com/CKBalance/ckb-sdk-dart.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
